title: Kevin Son â€“ Product Designer
logo:  # you can add own logo.
description: A Designer love food.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://sonkd.com" # the base hostname & protocol for your site, e.g. http://example.com

# Author Settings
author:
  name: Kevin Kim
  image: '/assets/img/profile.jpg'
  job: Product Designer
  bio: I'm a product designer living in Hanoi, Vietnam, with a <a href="/archive/#culinary">love for food</a>.
  email: sonkdbk@gmail.com
  play: "https://play.sonkd.com"

# Contact links
contact:
  - name: Twitter
    link: https://twitter.com/TieuNuiDesign
  - name: Medium
    link: https://medium.com/@sonkd
  - name: Github
    link: https://github.com/sonkd
  - name: Linkedin
    link: https://www.linkedin.com/in/kevinsonkd/

# Comment Section (Disqus)
disqus:
  shortname: sonkd

# Google Analytics
google-analytics: G-Q7TE8E3445 # add your identifier. For example UA-99631805-1.

# Build settings
markdown: kramdown
permalink: pretty
plugins:
  - jekyll-sitemap
  - jemoji
  - jekyll-paginate
  - jekyll-paginate-multiple
  - jekyll-seo-tag
  - jekyll/tagging
  - jekyll-feed

collections_dir: collections
collections:
  projects:
    output: true
    permalink: /projects/:name
  blog:
    output: true
    permalink: /blog/:name
  micro:
    output: true
    permalink: /micro/:name
  research:
    output: true
    permalink: /research/:name

paginate_multiple:
  - paginate: 10
    paginate_path: '/blog/page:num/'
    sub_dir: '/blog'
  - paginate: 10
    paginate_path: '/projects/page:num/'
    sub_dir: '/projects'

# Pages Path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext

feed:
  collections:
    - blog
    - micro
    - projects
    - research

include:
  - _pages

# Tags
tag_page_dir: tag
tag_page_layout: tag-page
tag_permalink_style: pretty

future: true

sass:
  sass_dir: _sass
  style: compressed

# Exclude from processing.
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - Gemfile
  - Gemfile.lock
  - vendor
  - node_modules/
